### ISSUE TITLE
Provided example does not work

### ISSUE THREAD

**Issue by sarthi2395** [curso-r/shinyhttr#1]
I am trying to use shinyhttr in a shiny app. To test how this works, I ran the example app provided, but with a different URL due to firewall restrictions. This is my code

````
library(shiny)
library(shinyWidgets)
library(httr)
library(shinyhttr)

ui <- fluidPage(
  
  sidebarLayout(
    
    NULL,
    
    mainPanel(
      actionButton('download', 'Download 100MB file...'),
      tags$p("see R console to compare both progress bars."),
      progressBar(
        id = "pbar",
        value = 0,
        title = "",
        display_pct = TRUE
      )
    )
  )
)

server <- function(input, output, session) {
  observeEvent(input$download, {
    GET(
      url = "https://ftp.ncbi.nih.gov/1000genomes/ftp/1000G_2504_high_coverage/data/ERR3239276/NA06985.final.cram",
      shinyhttr::progress(session, id = "pbar")
    )
  })
}

shinyApp(ui, server)
````

I see that the download starts fine and the progress bar in console gets updated, but the bar within shiny app doesn't. Am I missing something here?

**Comment by Athospd** [comment]
Weird problem. I fixed this by not using 'total' arg from `shinyWidgets::updateProgressBar()`. 

thanks. 
please use github version for now. CRAN use to take a while for accept changes.
